//
// Generated file, do not edit! Created by nedtool 5.0 from Frame.msg.
//

#ifndef __FRAME_M_H
#define __FRAME_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Frame.msg:3</tt> by nedtool.
 * <pre>
 * packet Frame
 * {
 *     string DestAddr;
 *     string SrcAddr;
 * 
 * }
 * </pre>
 */
class Frame : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string DestAddr;
    ::omnetpp::opp_string SrcAddr;

  private:
    void copy(const Frame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Frame&);

  public:
    Frame(const char *name=nullptr, int kind=0);
    Frame(const Frame& other);
    virtual ~Frame();
    Frame& operator=(const Frame& other);
    virtual Frame *dup() const {return new Frame(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getDestAddr() const;
    virtual void setDestAddr(const char * DestAddr);
    virtual const char * getSrcAddr() const;
    virtual void setSrcAddr(const char * SrcAddr);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Frame& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Frame& obj) {obj.parsimUnpack(b);}


#endif // ifndef __FRAME_M_H

